services:
  frontend:
    build:
      context: ./KiltaSphereClient
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./KiltaSphereClient:/app
      - /app/node_modules 
    tty: true